/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet.java.pkg2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Jason Kitio
 */
public class AddSignalement extends javax.swing.JFrame {

    /**
     * Creates new form AddSignalement
     */
    public AddSignalement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLog2 = new javax.swing.JButton();
        jLog3 = new javax.swing.JButton();
        jLog4 = new javax.swing.JButton();
        jLog5 = new javax.swing.JButton();
        TQuartier = new javax.swing.JTextField();
        bLog = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLog6 = new javax.swing.JButton();
        TVille = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CmbProximiter = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLog2.setBackground(new java.awt.Color(204, 204, 204));
        jLog2.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        jLog2.setForeground(new java.awt.Color(0, 0, 0));
        jLog2.setText("Se deconnecter");
        jLog2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jLog2ComponentResized(evt);
            }
        });
        jLog2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLog2ActionPerformed(evt);
            }
        });

        jLog3.setBackground(new java.awt.Color(204, 204, 204));
        jLog3.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        jLog3.setForeground(new java.awt.Color(0, 0, 0));
        jLog3.setText("Setting");
        jLog3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jLog3ComponentResized(evt);
            }
        });
        jLog3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLog3ActionPerformed(evt);
            }
        });

        jLog4.setBackground(new java.awt.Color(204, 204, 204));
        jLog4.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        jLog4.setForeground(new java.awt.Color(0, 0, 0));
        jLog4.setText("Liste");
        jLog4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jLog4ComponentResized(evt);
            }
        });
        jLog4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLog4ActionPerformed(evt);
            }
        });

        jLog5.setBackground(new java.awt.Color(204, 204, 204));
        jLog5.setFont(new java.awt.Font("Segoe UI", 3, 19)); // NOI18N
        jLog5.setForeground(new java.awt.Color(0, 0, 0));
        jLog5.setText("Signaler");
        jLog5.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jLog5ComponentResized(evt);
            }
        });
        jLog5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLog5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLog5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLog4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLog3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLog2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLog5)
                .addGap(18, 18, 18)
                .addComponent(jLog4)
                .addGap(18, 18, 18)
                .addComponent(jLog3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(238, Short.MAX_VALUE)
                    .addComponent(jLog2)
                    .addContainerGap()))
        );

        TQuartier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TQuartierActionPerformed(evt);
            }
        });

        bLog.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        bLog.setText("Signaler");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Quartier");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("proximité géographique");

        jLog6.setBackground(new java.awt.Color(204, 204, 204));
        jLog6.setFont(new java.awt.Font("Segoe UI", 3, 19)); // NOI18N
        jLog6.setForeground(new java.awt.Color(0, 0, 0));
        jLog6.setText("Send");
        jLog6.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jLog6ComponentResized(evt);
            }
        });
        jLog6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLog6ActionPerformed(evt);
            }
        });

        TVille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TVilleActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Ville");

        CmbProximiter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CmbProximiter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zone Éducative", "Zone Médicale", "Zone Commerciale" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLog6, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CmbProximiter, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TQuartier, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TVille, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(96, 96, 96)
                                                .addComponent(bLog))
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(59, 59, 59))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bLog)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TQuartier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CmbProximiter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 37, Short.MAX_VALUE)
                .addComponent(jLog6)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLog2ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLog2ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jLog2ComponentResized

    private void jLog2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLog2ActionPerformed
        Login fen = new Login();
        fen.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLog2ActionPerformed

    private void jLog3ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLog3ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jLog3ComponentResized

    private void jLog3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLog3ActionPerformed
        Users fen = new Users();
        fen.setVisible(true);
        this.setVisible(false);           // TODO add your handling code here:
    }//GEN-LAST:event_jLog3ActionPerformed

    private void jLog4ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLog4ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jLog4ComponentResized

    private void jLog4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLog4ActionPerformed
        Liste fen = new Liste();
        fen.setVisible(true);
        this.setVisible(false);           // TODO add your handling code here:
    }//GEN-LAST:event_jLog4ActionPerformed

    private void jLog5ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLog5ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jLog5ComponentResized

    private void jLog5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLog5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLog5ActionPerformed

    private void TQuartierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TQuartierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TQuartierActionPerformed

    private void jLog6ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLog6ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jLog6ComponentResized

    private void jLog6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLog6ActionPerformed
        try {
            //Charger le pilote
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_hygene", "root", "");

            String ville = TVille.getText();
            String quartier = TQuartier.getText();
            String proximiter = CmbProximiter.getSelectedItem().toString();

            System.out.println("Valeur sélectionnée : " + proximiter);

            PreparedStatement st = con.prepareStatement("insert into Signaler  values (?,?,?)");
            st.setString(1, ville);
            st.setString(2, quartier);
            st.setString(3, proximiter);
            st.executeUpdate();

            JOptionPane.showMessageDialog(null, "Insertion reussie");
            System.out.println("Insertion reussie");

            TVille.setText("");
            TQuartier.setText("");
            CmbProximiter.getItemAt(1);

        } catch (Exception e) {
            String proximiter = CmbProximiter.getSelectedItem().toString();
            JOptionPane.showMessageDialog(null, "Ajout non effectuer" + e + " " + proximiter);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLog6ActionPerformed

    private void TVilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TVilleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TVilleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSignalement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSignalement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSignalement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSignalement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSignalement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbProximiter;
    private javax.swing.JTextField TQuartier;
    private javax.swing.JTextField TVille;
    private javax.swing.JLabel bLog;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jLog2;
    private javax.swing.JButton jLog3;
    private javax.swing.JButton jLog4;
    private javax.swing.JButton jLog5;
    private javax.swing.JButton jLog6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
