/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet.java.pkg2;

/**
 *
 * @author Massemo
 */
public class Signaler extends javax.swing.JFrame {

    /**
     * Creates new form Signaler
     */
    public Signaler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLog2 = new javax.swing.JButton();
        jLog3 = new javax.swing.JButton();
        jLog4 = new javax.swing.JButton();
        jLog5 = new javax.swing.JButton();
        jLog1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLog2.setBackground(new java.awt.Color(204, 204, 204));
        jLog2.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        jLog2.setForeground(new java.awt.Color(0, 0, 0));
        jLog2.setText("Ce deconnecter");
        jLog2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jLog2ComponentResized(evt);
            }
        });
        jLog2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLog2ActionPerformed(evt);
            }
        });

        jLog3.setBackground(new java.awt.Color(204, 204, 204));
        jLog3.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        jLog3.setForeground(new java.awt.Color(0, 0, 0));
        jLog3.setText("Setting");
        jLog3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jLog3ComponentResized(evt);
            }
        });
        jLog3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLog3ActionPerformed(evt);
            }
        });

        jLog4.setBackground(new java.awt.Color(204, 204, 204));
        jLog4.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        jLog4.setForeground(new java.awt.Color(0, 0, 0));
        jLog4.setText("Liste");
        jLog4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jLog4ComponentResized(evt);
            }
        });
        jLog4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLog4ActionPerformed(evt);
            }
        });

        jLog5.setBackground(new java.awt.Color(204, 204, 204));
        jLog5.setFont(new java.awt.Font("Segoe UI", 3, 19)); // NOI18N
        jLog5.setForeground(new java.awt.Color(0, 0, 0));
        jLog5.setText("Signaler");
        jLog5.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jLog5ComponentResized(evt);
            }
        });
        jLog5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLog5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLog5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLog4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLog3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLog2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLog5)
                .addGap(18, 18, 18)
                .addComponent(jLog4)
                .addGap(18, 18, 18)
                .addComponent(jLog3)
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(238, Short.MAX_VALUE)
                    .addComponent(jLog2)
                    .addContainerGap()))
        );

        jLog1.setBackground(new java.awt.Color(204, 204, 204));
        jLog1.setFont(new java.awt.Font("Segoe UI", 3, 19)); // NOI18N
        jLog1.setForeground(new java.awt.Color(0, 0, 0));
        jLog1.setText("Ajouter un signalement");
        jLog1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jLog1ComponentResized(evt);
            }
        });
        jLog1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLog1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLog1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLog1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLog1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLog1ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jLog1ComponentResized

    private void jLog1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLog1ActionPerformed
        // TODO add your handling code here:
        AddSignalement fen = new AddSignalement();
        fen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLog1ActionPerformed

    private void jLog3ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLog3ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jLog3ComponentResized

    private void jLog3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLog3ActionPerformed
        Users fen = new Users();
        fen.setVisible(true);
        this.setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_jLog3ActionPerformed

    private void jLog4ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLog4ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jLog4ComponentResized

    private void jLog4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLog4ActionPerformed
        Liste fen = new Liste();
        fen.setVisible(true);
        this.setVisible(false);     }//GEN-LAST:event_jLog4ActionPerformed

    private void jLog5ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLog5ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jLog5ComponentResized

    private void jLog5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLog5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLog5ActionPerformed

    private void jLog2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLog2ActionPerformed
        Login fen = new Login();
        fen.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jLog2ActionPerformed

    private void jLog2ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLog2ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jLog2ComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signaler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signaler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signaler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signaler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signaler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jLog1;
    private javax.swing.JButton jLog2;
    private javax.swing.JButton jLog3;
    private javax.swing.JButton jLog4;
    private javax.swing.JButton jLog5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
