/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet.java.pkg2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Massemo
 */
public class SingIn extends javax.swing.JFrame {

    /**
     * Creates new form SingIn
     */
    public SingIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bAnnuler = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bUsername = new javax.swing.JLabel();
        bPassword = new javax.swing.JLabel();
        bConfirmP = new javax.swing.JLabel();
        TUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLog = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bAnnuler1 = new javax.swing.JButton();
        TPassword = new javax.swing.JPasswordField();
        TConfigPassword = new javax.swing.JPasswordField();
        jLog1 = new javax.swing.JButton();

        bAnnuler.setBackground(new java.awt.Color(204, 204, 204));
        bAnnuler.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bAnnuler.setForeground(new java.awt.Color(0, 0, 0));
        bAnnuler.setText("Annuler");
        bAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnnulerActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel1.setText("Creation De Compte");

        bUsername.setText("Username");

        bPassword.setText("Password");

        bConfirmP.setText("Confirm Password");

        jLabel2.setBackground(new java.awt.Color(51, 51, 255));
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Forget password");

        jLog.setBackground(new java.awt.Color(204, 204, 204));
        jLog.setFont(new java.awt.Font("Segoe UI", 3, 19)); // NOI18N
        jLog.setForeground(new java.awt.Color(0, 0, 0));
        jLog.setText("Sign up");
        jLog.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jLogComponentResized(evt);
            }
        });
        jLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jason Kitio\\Documents\\Gestion Hygiene total\\Back - End\\public\\Application Hygiène\\p2.png")); // NOI18N

        bAnnuler1.setBackground(new java.awt.Color(204, 204, 204));
        bAnnuler1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bAnnuler1.setForeground(new java.awt.Color(0, 0, 0));
        bAnnuler1.setText("Annuler");
        bAnnuler1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnnuler1ActionPerformed(evt);
            }
        });

        TConfigPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TConfigPasswordActionPerformed(evt);
            }
        });

        jLog1.setBackground(new java.awt.Color(204, 204, 204));
        jLog1.setFont(new java.awt.Font("Segoe UI", 3, 19)); // NOI18N
        jLog1.setForeground(new java.awt.Color(0, 0, 0));
        jLog1.setText("Login");
        jLog1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jLog1ComponentResized(evt);
            }
        });
        jLog1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLog1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLog1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bPassword)
                            .addComponent(bUsername)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TUsername, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(TConfigPassword, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(bConfirmP, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLog, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(bAnnuler1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addComponent(bUsername)
                        .addGap(18, 18, 18)
                        .addComponent(TUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bPassword)
                        .addGap(18, 18, 18)
                        .addComponent(TPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(bConfirmP)
                        .addGap(18, 18, 18)
                        .addComponent(TConfigPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLog1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLog)
                            .addComponent(bAnnuler1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnnulerActionPerformed
        TUsername.setText("");
        TPassword.setText("");
        TConfigPassword.setText("");

    }//GEN-LAST:event_bAnnulerActionPerformed

    private void bAnnuler1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnnuler1ActionPerformed
        TUsername.setText("");
        TPassword.setText("");
        TConfigPassword.setText("");
    }//GEN-LAST:event_bAnnuler1ActionPerformed

    private void jLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogActionPerformed
        // TODO add your handling code here:
        try {
            //Charger le Pilote
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_hygene", "root", "");

            //Recuperer le elements des champs respectifs
            String Username = TUsername.getText();
            String Password = TPassword.getText();
            String ConfimPassword = TConfigPassword.getText();
            if (Password == ConfimPassword) {
                // Comparer avec les donnees de la BD
                PreparedStatement st = con.prepareStatement("SELECT*FROM TUser WHERE Username=? AND Password=? ");
                st.setString(1, Username);
                st.setString(2, Password);
                ResultSet rs = st.executeQuery();
                if (rs.next() == true) {
                    SingIn sing = new SingIn();
                    this.setVisible(false);
                    sing.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Creation de compte echoue");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLogActionPerformed

    private void TConfigPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TConfigPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TConfigPasswordActionPerformed

    private void jLogComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLogComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jLogComponentResized

    private void jLog1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLog1ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jLog1ComponentResized

    private void jLog1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLog1ActionPerformed
        // TODO add your handling code here:
                Login fen = new Login();
                fen.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_jLog1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SingIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SingIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SingIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SingIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SingIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField TConfigPassword;
    private javax.swing.JPasswordField TPassword;
    private javax.swing.JTextField TUsername;
    private javax.swing.JButton bAnnuler;
    private javax.swing.JButton bAnnuler1;
    private javax.swing.JLabel bConfirmP;
    private javax.swing.JLabel bPassword;
    private javax.swing.JLabel bUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jLog;
    private javax.swing.JButton jLog1;
    // End of variables declaration//GEN-END:variables
}
