/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet.java.pkg2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Jason Kitio
 */
public class Users extends javax.swing.JFrame {

    /**
     * Creates new form Users
     */
    public Users() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bLog = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLog2 = new javax.swing.JButton();
        jLog3 = new javax.swing.JButton();
        jLog4 = new javax.swing.JButton();
        jLog5 = new javax.swing.JButton();
        jLog6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bLog.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        bLog.setText("Signaler");

        jLog2.setBackground(new java.awt.Color(204, 204, 204));
        jLog2.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        jLog2.setForeground(new java.awt.Color(0, 0, 0));
        jLog2.setText("Se deconnecter");
        jLog2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jLog2ComponentResized(evt);
            }
        });
        jLog2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLog2ActionPerformed(evt);
            }
        });

        jLog3.setBackground(new java.awt.Color(204, 204, 204));
        jLog3.setFont(new java.awt.Font("Segoe UI", 3, 19)); // NOI18N
        jLog3.setForeground(new java.awt.Color(0, 0, 0));
        jLog3.setText("Setting");
        jLog3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jLog3ComponentResized(evt);
            }
        });
        jLog3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLog3ActionPerformed(evt);
            }
        });

        jLog4.setBackground(new java.awt.Color(204, 204, 204));
        jLog4.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        jLog4.setForeground(new java.awt.Color(0, 0, 0));
        jLog4.setText("Liste");
        jLog4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jLog4ComponentResized(evt);
            }
        });
        jLog4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLog4ActionPerformed(evt);
            }
        });

        jLog5.setBackground(new java.awt.Color(204, 204, 204));
        jLog5.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        jLog5.setForeground(new java.awt.Color(0, 0, 0));
        jLog5.setText("Signaler");
        jLog5.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jLog5ComponentResized(evt);
            }
        });
        jLog5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLog5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLog5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLog4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLog3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLog2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLog5)
                .addGap(18, 18, 18)
                .addComponent(jLog4)
                .addGap(18, 18, 18)
                .addComponent(jLog3)
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(238, Short.MAX_VALUE)
                    .addComponent(jLog2)
                    .addContainerGap()))
        );

        jLog6.setBackground(new java.awt.Color(204, 204, 204));
        jLog6.setFont(new java.awt.Font("Segoe UI", 3, 19)); // NOI18N
        jLog6.setForeground(new java.awt.Color(0, 0, 0));
        jLog6.setText("Update");
        jLog6.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jLog6ComponentResized(evt);
            }
        });
        jLog6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLog6ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Username");

        tUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUsernameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Password");

        tPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(bLog))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(tUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                    .addComponent(tPassword))))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLog6, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bLog)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLog6)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLog2ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLog2ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jLog2ComponentResized

    private void jLog2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLog2ActionPerformed
        Login fen = new Login();
        fen.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLog2ActionPerformed

    private void jLog3ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLog3ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jLog3ComponentResized

    private void jLog3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLog3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLog3ActionPerformed

    private void jLog4ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLog4ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jLog4ComponentResized

    private void jLog4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLog4ActionPerformed
        Liste fen = new Liste();
        fen.setVisible(true);
        this.setVisible(false);   // TODO add your handling code here:
    }//GEN-LAST:event_jLog4ActionPerformed

    private void jLog5ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLog5ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jLog5ComponentResized

    private void jLog5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLog5ActionPerformed
        Signaler fen = new Signaler();
        fen.setVisible(true);
        this.setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_jLog5ActionPerformed

    private void jLog6ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLog6ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jLog6ComponentResized

    private void jLog6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLog6ActionPerformed
        try {
            //Charger le pilote
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_hygene", "root", "");

            String Username = tUsername.getText();
            String Password = tPassword.getText();

            PreparedStatement st = con.prepareStatement("update user set  Username = ?,Password = ? ");
            st.setString(1, Username);
            st.setString(2, Password);
            st.executeUpdate();

            JOptionPane.showMessageDialog(null, "Insertion reussie");
            System.out.println("Mise a jour reussie");

            tUsername.setText("");
            tPassword.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Mise a jour non effectuer");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLog6ActionPerformed

    private void tUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tUsernameActionPerformed

    private void tPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Users().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bLog;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jLog2;
    private javax.swing.JButton jLog3;
    private javax.swing.JButton jLog4;
    private javax.swing.JButton jLog5;
    private javax.swing.JButton jLog6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tUsername;
    // End of variables declaration//GEN-END:variables
}
